routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

// The Home Page
Route::get('/', array(
	'uses' 	=> 'PagesController@home',
	'as' 	=> 'pages.home'
));

/*
|--------------------------------------------------------------------------
| Category Routes
|--------------------------------------------------------------------------
|
| All Routes pertaining to Categories are defined here. These routes are
| prefixed by the 'categories' noun, and use the '{category}' wildcard
| when necessary. The Route Names are prefixed with 'categories'.
|
*/
Route::resource('categories', 'CategoriesController', [
	'parameters' => 'singular'
]);

/*
|--------------------------------------------------------------------------
| Popup Routes
|--------------------------------------------------------------------------
|
| Routes to popup dialogs.
| If accessed with AJAX calls returns views contained in a single div.
| If accessed directly from the browser, a different standalone view can be delivered if it exist.
|
*/
Route::get('/file/upload', array(
	'uses' => 'PopupController@getUploadFileView',
	'as' => 'file.upload'
));

Route::get('/user/login', array(
	'uses' => 'PopupController@getLoginView',
	'as' => 'user.login'
));

/*
|--------------------------------------------------------------------------
| File Routes
|--------------------------------------------------------------------------
|
| All Routes pertaining to files are defined here. These routes are
| prefixed by the 'file' noun, and use the '{file}' wildcard
| when necessary. The Route Names are prefixed with 'file'.
|
*/
Route::put('/file/upload', array(
	'uses' => 'UploadController@upload',
	'as' => 'file.upload'
));

/*
|--------------------------------------------------------------------------
| Addon Routes
|--------------------------------------------------------------------------
|
| All Routes pertaining to Addons are defined here. These routes are
| prefixed by the 'addon' noun, and use the '{addon}' wildcard
| when necessary. The Route Names are prefixed with 'addon'.
|
*/
Route::resource('addon', 'AddonController', [
	'except' => 'index'
]);

/*
|--------------------------------------------------------------------------
| BLSave Routes
|--------------------------------------------------------------------------
|
| All Routes pertaining to Saves are defined here. These routes are
| prefixed by the 'save' noun, and use the '{save}' wildcard
| when necessary. The Route Names are prefixed with 'save'.
|
*/
Route::resource('save', 'BlocklandSaveController', [
	'except' => 'index'
]);

/*
|--------------------------------------------------------------------------
| User Routes
|--------------------------------------------------------------------------
|
| All Routes pertaining to Users are defined here. These routes are
| prefixed by the 'user' noun, and use the '{user}' wildcard
| when necessary. The Route Names are prefixed with 'user'.
|
*/
Route::post('/user/login', array(
	'uses' => 'Auth\LoginController@login',
	'as' => 'user.login'
));
Route::get('/user/logout', array(
	'uses' => 'Auth\LoginController@logout',
	'as' => 'user.logout',
	'middleware' => 'auth'
));

Route::get('/user/register', array(
	'uses' => 'Auth\RegisterController@showRegistrationForm',
	'as' => 'user.register'
));
Route::post('/user/register', array(
	'uses' => 'Auth\RegisterController@register',
	'as' => 'user.register'
));

Route::get('/user/show/{user?}', array(
	'uses' => 'UserController@show',
	'as' => 'user.show'
));
Route::get('/user/edit', array(
	'uses' => 'UserController@edit',
	'as' => 'user.edit',
	'middleware' => 'auth'
));
Route::put('/user/update', array(
	'uses' => 'UserController@update',
	'as' => 'user.update',
	'middleware' => 'auth'
));

Route::get('/auth/ip', array(
	'uses' => 'UserController@validateAuthIp',
	'as' => 'auth.ip',
	'middleware' => ['api', 'auth']
));

/*
|--------------------------------------------------------------------------
| Password Routes
|--------------------------------------------------------------------------
|
| All Routes pertaining to Passwords are defined here. These routes are
| prefixed by the 'password' noun, and use the '{token}' wildcard
| when necessary. The Route Names are prefixed with 'password'.
|
*/
Route::get('/password/email', array(
	'uses' => 'Auth\ForgotPasswordController@showLinkRequestForm',
	'as' => 'password.email'
));
Route::post('/password/email', array(
	'uses' => 'Auth\ForgotPasswordController@sendResetLinkEmail',
	'as' => 'password.email'
));
Route::get('/password/reset/{token}', array(
	'uses' => 'Auth\ResetPasswordController@showResetForm',
	'as' => 'password.reset'
));
Route::post('/password/reset', array(
	'uses' => 'Auth\ResetPasswordController@reset',
	'as' => 'password.reset'
));

app/Models/Repository.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

use App\Models\Traits\FormatSize;
use App\Repository\Blockland\Addon\File as AddonFile;

class Repository extends Model
{
	//////////////
	//* Traits *//
	//////////////
	use FormatSize;

	//////////////////
	//* Attributes *//
	//////////////////
	/**
	 * The Attributes that are hidden.
	 *
	 * @var string
	 */
	protected $hidden = ['id', 'category_id'];

	/**
	 * The Attributes that are allowed to be Mass Assigned.
	 *
	 * @var array
	 */
	protected $fillable = ['name', 'slug', 'description'];

	// TODO: Add slug version that will determine what version to take
	// slug_version = version | channel.version | slug_version | slug_channel.version

	/////////////////////
	//* Boot Override *//
	/////////////////////
	/**
	 * This method handles any triggers associated with this Model.
	 *
	 * @return void
	 */
	public static function boot()
	{
		parent::boot();
		
		// Deleting the model
		static::deleting(function($repository)
		{
			foreach ($repository->channels as $channel)
				$channel->delete();
		});

		// Model was created
		static::created(function($repository)
		{
			$repository->createChannel('release', true);
		});
	}

	/////////////////////
	//* Relationships *//
	/////////////////////
	/**
	 * Returns the Channels that this Repository has.
	 *
	 * @return Relationship
	 */
	public function channels()
	{
		return $this->hasMany(Channel::class);
	}

	/**
	 * Returns the default Channel that this Repository has.
	 *
	 * @return Relationship
	 */
	public function channel()
	{
		return $this->hasOne(Channel::class)->where("default", true);
	}

	/**
	 * Returns the Versions that this Repository has.
	 *
	 * @return Relationship
	 */
	public function versions()
	{
		return $this->hasManyThrough(Version::class, Channel::class);
	}

	/**
	 * Returns the default Version that this Repository has.
	 *
	 * @return Relationship
	 */
	public function version()
	{
		return $this->channel->version();
	}

	/**
	 * Returns the Users that this Repository belongs to.
	 *
	 * @return Relationship
	 */
	public function owners()
	{
		return $this->belongsToMany(User::class)->withTimestamps();
	}

	/**
	 * Returns the Authors that made this Repository.
	 *
	 * @return Relationship
	 */
	public function authors()
	{
		return $this->version->authors();
	}

	/**
	 * Returns the RepositoryType that this Repository belongs to.
	 *
	 * @return Relationship
	 */
	public function type()
	{
		return $this->belongsTo(RepositoryType::class, 'repository_type_id');
	}

	/**
	 * Returns the Category that this Repository belongs to.
	 *
	 * @return Relationship
	 */
	public function category()
	{
		return $this->belongsTo(Category::class);
	}

	/**
	 * Returns the Tag that this Repository has.
	 *
	 * @return Relationship
	 */
	public function tags()
	{
		return $this->morphToMany(Tag::class, 'taggable')->withTimestamps();
	}

	/////////////////
	//* Utilities *//
	/////////////////
	/**
	 * Returns the slug that is unique to this Repository.
	 *
	 * @param string $slug The slug unique to Repository.
	 *
	 * @return string
	 */
	public static function fromSlug($slug)
	{
		return self::where('slug', $slug)->first();
	}

	/**
	 * Returns the Repository that is unique to this filename.
	 *
	 * @param string $file The file identifying this Repository.
	 *
	 * @return string
	 */
	public static function fromFile($file)
	{
		// Find out about the file
		if ($file = File::fromFilename($file))
		{
			// Get the version
			$version = $file->link;
			if ($version instanceof Version)
			{
				// And we're done with the link
				return $version->repository;
			}
		}
		return NULL;
	}

	/**
	 * Returns true if User are owner to this Repository.
	 *
	 * @param User $user The User to check ownership.
	 *
	 * @return boolean
	 */
	public function isOwner(User $user)
	{
		return $this->owners->contains($user);
	}

	/**
	 * Updates the File with data from Repository and its relations.
	 *
	 * @return bool
	 */
	public function flush()
	{
		// Get needed models
		$channel = $this->channel;
		$version = $this->version;
		$cache = $version->cache;
		$file = $version->file;

		if (!$file->createTempFile())
			return false;

		// Load the addon
		$addon = new AddonFile($file->download_name);

		if (!$addon->Open(temp_path($file->path)))
		{
			$file->deleteTempFile();
			return false;
		}

		// Set internal data info
		$addon->title = $this->name;
		$addon->info->authors = $version->authors->pluck('name')->toArray();
		$addon->info->description = $version->summary;
		$addon->version->channel = $channel->name;
		$addon->version->version = $version->name;

		// Set repository info
		$addon->version->SetRepository(url('api'), 'json', $this->slug);

		$addon->Cleanup();

		$addon->Close();

		// Update crc value
		$crc = Blacklist\AddonCrcBlacklist::convertTo32(crc32($file->getTempContents()));
		$cache->crc = $crc;
		$cache->save();

		// Send to storage
		$file->saveTempFile();
		$file->deleteTempFile();
		$file->update();

		return true;
	}

	/**
	 * Create a Channel and return it.
	 *
	 * @param string $name The name of the Channel.
	 * @param bool $default Set as default Version.
	 *
	 * @return Channel
	 */
	public function createChannel($name, $default = false)
	{
		$channel_obj = new Channel;
		$channel_obj->name = $name;
		$channel_obj->slug = $this->slug.'_'.str_slug($name);
		$this->channels()->save($channel_obj);
		if ($default)
			$channel_obj->default = $default;
		return $channel_obj;
	}

	///////////////////////////
	//* Attribute Overrides *//
	///////////////////////////
	// Note: All attributes should later on read from default version or defined slug
	/**
	 * Get the size of the Repository,
	 *
	 * @return string
	 */
	public function getSizeAttribute()
	{
		return $this->version->file->size;
	}

	/**
	 * Get the size in metric of the Repository.
	 *
	 * @return string
	 */
	public function getSizeMetAttribute()
	{
		return static::formatBytesMet($this->size);
	}

	/**
	 * Get the size in bin of the Repository.
	 *
	 * @return string
	 */
	public function getSizeBinAttribute()
	{
		return static::formatBytesBin($this->size);
	}

	/**
	 * Get the summary of the Repository.
	 *
	 * @return string
	 */
	public function getSummaryAttribute()
	{
		return $this->version->summary;
	}

	/**
	 * Set the summary of the Repository.
	 *
	 * @return void
	 */
	public function setSummaryAttribute($summary)
	{
		$this->version->update(['summary' => $summary]);
	}

	/**
	 * Get the description to be displayed on site.
	 *
	 * @return string
	 */
	public function getDescriptionHtmlAttribute()
	{
		return nl2br(e($this->description));
	}

	/**
	 * Get the Version name of the Repository.
	 *
	 * @return string
	 */
	public function getVersionNameAttribute()
	{
		return $this->version->name;
	}

	/**
	 * Get amounts of downloads of the Repository.
	 *
	 * @return int
	 */
	public function getDownloadsAttribute()
	{
		// TODO: Read from statistics table
		return 0;
	}

	/**
	 * Get the User uploader of the Repository.
	 *
	 * @return App\Models\User
	 */
	public function getUploaderAttribute()
	{
		return $this->version->file->uploader;
	}

	/**
	 * Get the file name of the Repository.
	 *
	 * @return string
	 */
	public function getFilenameAttribute()
	{
		return $this->version->file->download_name;
	}

	/**
	 * Get the CRC calculation of the Repository.
	 *
	 * @return string
	 */
	public function getCrcAttribute()
	{
		return ($cache = $this->version->cache) ? $cache->crc : '';
	}

	/**
	 * Get the route link of the Repository.
	 *
	 * @return string
	 */
	public function getRouteAttribute()
	{
		return route($this->type->name.'.show', $this->slug);
	}

	/**
	 * Get the download link of the Repository.
	 *
	 * @return string
	 */
	public function getDownloadLinkAttribute()
	{
		return '/api/mod/'.$this->slug.'.zip';
	}
}

resources/views/resources/addon/corrections.blade.php
{{-- Corrections --}}
{{-- Check App\Validation\Rules for possible messages --}}
@if (count($error) > 0)
	<h2>Warnings</h2>

	{{-- Invalid description --}}
	@if ($error->has('info_invalid'))
		<div class="row form-group">
			<div class="col-xs-12 col-sm-8 col-sm-offset-2">
				Description is required and will be created
			</div>
		</div>
	@endif
	{{-- Missing namecheck --}}
	@if ($error->has('namecheck_missing'))
		<div class="row form-group">
			<div class="col-xs-12 col-sm-8 col-sm-offset-2">
				{{ Form::checkbox('namecheck_missing', 1, false, ['id' => 'namecheck_missing']) }}
				{{ Form::label('namecheck_missing', 'Create namecheck', ['class' => 'checkbox-inline blr-checkbox']) }}
			</div>
		</div>
	@endif
	{{-- Invalid namecheck --}}
	@if ($error->has('namecheck_invalid'))
		<div class="row form-group">
			<div class="col-xs-12 col-sm-8 col-sm-offset-2">
				{{ Form::checkbox('namecheck_invalid', 1, true, ['id' => 'namecheck_invalid']) }}
				{{ Form::label('namecheck_invalid', 'Fix namecheck', ['class' => 'checkbox-inline blr-checkbox']) }}
			</div>
		</div>
	@endif
	{{-- Invalid version --}}
	@if ($error->has('version_invalid'))
		<div class="row form-group">
			<div class="col-xs-12 col-sm-8 col-sm-offset-2">
				Version is invalid and needs to be corrected
			</div>
		</div>
	@endif
@endif

resources/views/resources/addon/create.blade.php
@extends('layouts.master')

@section('title', 'Create Add-On')

@section('mainbox', 'upload')

@section('content')
	<div class="container-fluid">
		{{ Form::open(['route' => 'addon.store', 'method' => 'post', 'files' => true, 'class' => 'form-horizontal']) }}
		<fieldset class="blr-fieldset">
			<legend>Create Add-On</legend>
			<div class="row">
				{{-- Category --}}
				<div class="row form-group">
					<div class="col-xs-12 text-xs-left col-sm-2 hug-sm-right">
						{{ Form::label('category', 'Category:', ['class' => 'control-label control-label-blr']) }}
					</div>
					<div class="col-xs-12 col-sm-8">
						{{ Form::select('category', $categories, $category, ['required' => 'true', 'class' => 'form-control blr-form-control']) }}
					</div>
				</div>

				{{-- Title --}}
				<div class="row form-group">
					<div class="col-xs-12 text-xs-left col-sm-2 hug-sm-right">
						{{ Form::label('title', 'Title:', ['class' => 'control-label control-label-blr']) }}
					</div>
					<div class="col-xs-12 col-sm-8">
						{{ Form::text('title', $title, ['required' => 'true', 'class' => 'form-control blr-form-control']) }}
					</div>
				</div>

				{{-- Summary --}}
				<div class="row form-group">
					<div class="col-xs-12 text-xs-left col-sm-2 hug-sm-right">
						{{ Form::label('summary', 'Summary:', ['class' => 'control-label control-label-blr']) }}
					</div>
					<div class="col-xs-12 col-sm-8">
						{{ Form::text('summary', $summary, ['required' => 'true', 'class' => 'form-control blr-form-control']) }}
					</div>
				</div>

				{{-- Authors --}}
				<div class="row form-group">
					<div class="col-xs-12 text-xs-left col-sm-2 hug-sm-right">
						{{ Form::label('authors', 'Authors:', ['class' => 'control-label control-label-blr']) }}
					</div>
					<div class="col-xs-12 col-sm-8">
						{{ Form::text('authors', $authors, ['required' => 'true', 'class' => 'form-control blr-form-control']) }}
					</div>
				</div>

				{{-- Description --}}
				<div class="row form-group">
					<div class="col-xs-12 text-xs-left col-sm-2 hug-sm-right">
						{{ Form::label('description', 'Description:', ['class' => 'control-label control-label-blr']) }}
					</div>
					<div class="col-xs-12 col-sm-8">
						{{ Form::textarea('description', $description, ['class' => 'form-control blr-form-control']) }}
					</div>
				</div>

				<div class="row form-group">
					{{-- Channel --}}
					<div class="col-xs-12 text-xs-left col-sm-2 hug-sm-right">
						{{ Form::label('channel', 'Channel:', ['class' => 'control-label control-label-blr']) }}
					</div>
					<div class="col-xs-12 col-sm-4">
						{{ Form::text('channel', $channel, ['required' => 'true', 'class' => 'form-control blr-form-control']) }}
					</div>

					{{-- Version --}}
					<div class="col-xs-12 text-xs-left col-sm-1 hug-sm-right">
						{{ Form::label('version', 'Version:', ['class' => 'control-label control-label-blr']) }}
					</div>
					<div class="col-xs-12 col-sm-3">
						{{ Form::text('version', $version, ['required' => 'true', 'class' => 'form-control blr-form-control']) }}
					</div>
				</div>

				@include('resources.addon.corrections')

				<h2>Screenshots</h2>

				<div class="row">
					<div class="col-xs-12 col-sm-8 col-sm-offset-2">
						{{-- TODO: Proper file input. --}}
						{{ Form::file('screenshot') }}
					</div>
				</div>

				<div class="row">
					{{-- Create --}}
					<div class="col-xs-12 mar-xs-top col-sm-4 col-sm-push-6">
						{{ Form::submit('Create Add-On', ['class' => 'btn blr-btn btn-blr-default width-xs-full float-sm-right width-sm-auto']) }}
					</div>
				</div>

				@if (count($errors) > 0)
					<div class="row">
						<div class="col-xs-12">
							<ul>
								@foreach($errors->all() as $err)
									<li>{{ $err }}</li>
								@endforeach
							</ul>
						</div>
					</div>
				@endif
			</div>
		</fieldset>
		{{ Form::close() }}
	</div>
@endsection

resources/views/resources/addon/edit.blade.php
@extends('layouts.master')

@section('title', 'Edit ' . $addon->name)

@section('mainbox', 'edit')

@section('content')
	<div class="container-fluid">
		{{ Form::open(['route' => ['addon.update', $addon->slug], 'method' => 'put','files' => true, 'class' => 'form-horizontal']) }}
		<fieldset class="blr-fieldset">
			<legend>Edit Add-On</legend>
			<div class="row">
				{{-- Category --}}
				<div class="row form-group">
					<div class="col-xs-12 text-xs-left col-sm-2 hug-sm-right">
						{{ Form::label('category', 'Category:', ['class' => 'control-label control-label-blr']) }}
					</div>
					<div class="col-xs-12 col-sm-8">
						{{ Form::select('category', $categories, $addon->category_id, ['disabled', 'required' => 'true', 'class' => 'form-control blr-form-control']) }}
					</div>
				</div>

				{{-- Title --}}
				<div class="row form-group">
					<div class="col-xs-12 text-xs-left col-sm-2 hug-sm-right">
						{{ Form::label('title', 'Title:', ['class' => 'control-label control-label-blr']) }}
					</div>
					<div class="col-xs-12 col-sm-8">
						{{ Form::text('title', $addon->name, ['required' => 'true', 'class' => 'form-control blr-form-control']) }}
					</div>
				</div>

				{{-- Summary --}}
				<div class="row form-group">
					<div class="col-xs-12 text-xs-left col-sm-2 hug-sm-right">
						{{ Form::label('summary', 'Summary:', ['class' => 'control-label control-label-blr']) }}
					</div>
					<div class="col-xs-12 col-sm-8">
						{{ Form::text('summary', $addon->summary, ['required' => 'true', 'class' => 'form-control blr-form-control']) }}
					</div>
				</div>

				{{-- Authors --}}
				<div class="row form-group">
					<div class="col-xs-12 text-xs-left col-sm-2 hug-sm-right">
						{{ Form::label('authors', 'Authors:', ['class' => 'control-label control-label-blr']) }}
					</div>
					<div class="col-xs-12 col-sm-8">
						{{ Form::text('authors', $addon->authors->implode('name', ', '), ['required' => 'true', 'class' => 'form-control blr-form-control']) }}
					</div>
				</div>

				{{-- Description --}}
				<div class="row form-group">
					<div class="col-xs-12 text-xs-left col-sm-2 hug-sm-right">
						{{ Form::label('description', 'Description:', ['class' => 'control-label control-label-blr']) }}
					</div>
					<div class="col-xs-12 col-sm-8">
						{{ Form::textarea('description', $addon->description, ['class' => 'form-control blr-form-control']) }}
					</div>
				</div>

				<h2>Screenshots</h2>

				<div class="row">
					<div class="col-xs-12 col-sm-8 col-sm-offset-2">
						{{-- TODO: Proper file input. --}}
						{{ Form::file('screenshot') }}
					</div>
				</div>

				<div class="row">
					{{-- Update --}}
					<div class="col-xs-12 mar-xs-top col-sm-4 col-sm-push-6">
						{{ Form::submit('Update', ['class' => 'btn blr-btn btn-blr-default width-xs-full float-sm-right width-sm-auto']) }}
					</div>
				</div>

				@if (count($errors) > 0)
					<div class="row">
						<div class="col-xs-12">
							<ul>
								@foreach($errors->all() as $err)
									<li>{{ $err }}</li>
								@endforeach
							</ul>
						</div>
					</div>
				@endif
			</div>
		</fieldset>
		{{ Form::close() }}
		<div class="row mar-xs-top extend-xs-double mar-sm-top-none">
			{{-- Delete --}}
			<div class="col-xs-12">
				{{ Form::open(['route' => ['addon.destroy', $addon->slug], 'method' => 'delete', 'class' => 'form-horizontal']) }}
				{{ Form::submit('Delete Add-On', ['class' => 'btn blr-btn btn-blr-red width-xs-full float-sm-left width-sm-auto uppercase vpull-btn-sm-up']) }}
				{{ Form::close() }}
			</div>
		</div>
	</div>
@endsection

resources/views/resources/addon/show.blade.php
@extends('layouts.master')

@section('title', $addon->name . ' by ' . $addon->authors->implode('name', ', '))

@section('mainbox', 'view')

@section('content')
	{{-- Negative margin is needed so the download button can have a top margin for xs size. --}}
	<div class="container-fluid mar-xs-top-neg">
		<div class="row">
			@if(Auth::user() && $addon->IsOwner(Auth::user()))
				<div class="col-xs-12 col-sm-7 hug-xs-left nopad-xs-right mar-xs-top">
					<div class="col-xs-12 nopad-xs-both title">{{ $addon->name }}</div>
					<div class="col-xs-12 nopad-xs-both subtitle">by {{ $addon->authors->implode('name', ', ') }}</div>
					<div class="col-xs-12 nopad-xs-both summary">{{ $addon->summary }}</div>
				</div>
				<div class="col-xs-12 nopad-xs-right text-xs-center mar-xs-top col-sm-2">
					{{-- TODO: Dynamic add-on states. --}}
					<div class="col-xs-6 col-sm-12 addon-state state-public"></div>
					<div class="col-xs-6  mar-xs-top-half col-sm-12"><a
								href="{{ route('addon.edit', $addon->slug) }}">Edit</a>
					</div>
				</div>
				<div class="col-xs-12 mar-xs-top col-sm-3">
					<div class="col-xs-12 nopad-xs-both mar-xs-btm-half">
						<a class="btn blr-btn btn-blr-default width-xs-full"
						   href="{{ $addon->download_link }}">Download</a>
					</div>
					<div class="col-xs-12 filesize">{{ $addon->size_bin }}</div>
				</div>
			@else
				<div class="col-xs-12 mar-xs-top col-sm-10 hug-xs-left">
					<div class="col-xs-12 nopad-xs-both title">{{ $addon->name }}</div>
					<div class="col-xs-12 nopad-xs-both subtitle">by {{ $addon->authors->implode('name', ', ') }}</div>
					<div class="col-xs-12 nopad-xs-both summary">{{ $addon->summary }}</div>
				</div>
				<div class="col-xs-12 mar-xs-top col-sm-2 nopad-sm-left">
					<div class="col-xs-12 nopad-xs-both mar-xs-btm-half">
						<a class="btn blr-btn btn-blr-default width-xs-full"
						   href="{{ $addon->download_link }}">Download</a>
					</div>
					<div class="col-xs-12 filesize">{{ $addon->size_bin }}</div>
				</div>
			@endif
		</div>
		<hr class="mar-xs-btm-none">
		<div class="row inforow">
			{{-- TODO: Figure out nice separators like in the concept that work at xs scale. --}}
			<div class="col-xs-6 mar-xs-top-half col-sm-3">
				<div class="col-xs-12 info-key">Version</div>
				<div class="col-xs-12 info-value">{{ $addon->version_name }}</div>
			</div>
			<div class="col-xs-6 mar-xs-top-half col-sm-3">
				<div class="col-xs-12 info-key">Downloads</div>
				<div class="col-xs-12 info-value">{{ $addon->downloads }}</div>
			</div>
			<div class="col-xs-6 mar-xs-top-half col-sm-3">
				<div class="col-xs-12 info-key">Updated</div>
				<div class="col-xs-12 info-value">{{ date('Y-m-d', $addon->updated_at->getTimestamp()) }}</div>
			</div>
			<div class="col-xs-6 mar-xs-top-half col-sm-3">
				<div class="col-xs-12 info-key">Created</div>
				<div class="col-xs-12 info-value">{{ date('Y-m-d', $addon->created_at->getTimestamp()) }}</div>
			</div>
		</div>
		<hr class="mar-xs-top-half">
		<div class="row">
			<div class="col-xs-12 nopad-xs-both description">
				{!! $addon->description_html or '<p>No description.</p>' !!}
			</div>
			<div class="col-xs-12 nopad-xs-both text-xs-right mar-xs-top footnote">{{ $addon->filename }} uploaded by <a
						href="{{ route('user.show', $addon->uploader->id) }}">{{ $addon->uploader->username }}</a>
			</div>
		</div>
	</div>
@endsection